### ISSUE TITLE
-n/--no-build with make is ignored in 0.10.0

### ISSUE THREAD

**Issue by Atmelfan** [nickdiego/compiledb#83]
Trying to run `compiledb -n make` tries to build even with -n or --no-build.

Have tried on ubuntu 19.04 and Fedora 27, both produce identical results.

Steps to reproduce:

1. `pip3 install compiledb==0.9.8`
2. `compiledb -n make #works` 
3. `pip3 install compiledb==0.10.0`
2. `compiledb -n make #fails` 

Here is a cutout where I did this on an intentionally broken project:

```
atmelfan@gpa-thinkpad:~/Documents/solarbora/projects/src-inverter$ sudo pip3 install compiledb==0.10.0
Collecting compiledb==0.10.0
  Downloading https://files.pythonhosted.org/packages/f1/e9/66676cdfb6665b9b70e0660ea3306976d9f79c742c753d3e6594e60df629/compiledb-0.10.0-py3-none-any.whl
Requirement already satisfied: click in /usr/local/lib/python3.7/dist-packages (from compiledb==0.10.0) (7.0)
Requirement already satisfied: shutilwhich in /usr/local/lib/python3.7/dist-packages (from compiledb==0.10.0) (1.1.0)
Requirement already satisfied: bashlex in /usr/local/lib/python3.7/dist-packages (from compiledb==0.10.0) (0.14)
Installing collected packages: compiledb
  Found existing installation: compiledb 0.9.8
    Uninstalling compiledb-0.9.8:
      Successfully uninstalled compiledb-0.9.8
Successfully installed compiledb-0.10.0
atmelfan@gpa-thinkpad:~/Documents/solarbora/projects/src-inverter$ compiledb -n make
src/main.c: In function ‘main’:
src/main.c:100:7: error: ‘kgomrwaoyrpouiw’ undeclared (first use in this function)
      }kgomrwaoyrpouiw
       ^
src/main.c:100:7: note: each undeclared identifier is reported only once for each function it appears in
src/main.c:101:5: error: expected ‘;’ before ‘}’ token
     }
     ^
make: *** [Makefile:65: build/main.o] Error 1
atmelfan@gpa-thinkpad:~/Documents/solarbora/projects/src-inverter$ sudo pip3 install compiledb==0.9.8
Collecting compiledb==0.9.8
  Downloading https://files.pythonhosted.org/packages/f3/93/cf32ff4c28aa3d22e35ae6f3648abf3d67ffc068d6f946191a7647372857/compiledb-0.9.8-py3-none-any.whl
Requirement already satisfied: bashlex in /usr/local/lib/python3.7/dist-packages (from compiledb==0.9.8) (0.14)
Requirement already satisfied: click in /usr/local/lib/python3.7/dist-packages (from compiledb==0.9.8) (7.0)
Installing collected packages: compiledb
  Found existing installation: compiledb 0.10.0
    Uninstalling compiledb-0.10.0:
      Successfully uninstalled compiledb-0.10.0
Successfully installed compiledb-0.9.8
atmelfan@gpa-thinkpad:~/Documents/solarbora/projects/src-inverter$ compiledb -n make
## Processing build commands from 3
## Loaded compilation database with 6 entries from compile_commands.json
## Writing compilation database with 6 entries to compile_commands.json
## Done.
```

**Comment by nickdiego** [comment]
Hi, Thanks for reporting.

This issue has been fixed in #82 and should be available in just published [Release 0.10.1](https://github.com/nickdiego/compiledb/releases).

Appreciate your feedback.
